In [40]:
import pandas as pd
import numpy as np
import math
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_curve 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import GridSearchCV

In [3]:
datafile = "../iris.csv"
df = pd.read_csv(datafile, header = 0)

In [4]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [5]:
df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [8]:
feature_cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
x = df[feature_cols]
y = df.species

In [23]:
#Exemplo de "distância"
print("Amostra 1:", x_train[1,])
print("Amostra 2:", x_train[2,])

Amostra 1: [-0.11897377  1.8551145  -1.14624252 -1.13955497]
Amostra 2: [-0.95179019  1.37117159 -1.31488633 -1.2676634 ]


In [34]:
dist = math.sqrt((x_train[1,0] - x_train[2,0])**2 + (x_train[1,1] - x_train[2,1])**2 + (x_train[1,2] - x_train[2,2])**2 + (x_train[1,3] - x_train[2,3])**2)
print("Distância: ", dist)

Distância:  0.986223312974614


In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [10]:
scaler = StandardScaler()  
scaler.fit(x_train)

x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test) 

In [49]:
classifier = KNeighborsClassifier(n_neighbors = 5)  
classifier.fit(x_train, y_train)  
print(x_test)

[[ 0.          2.33905742 -1.42731553 -1.2676634 ]
 [-0.83281641 -1.29051444 -0.41545268 -0.11468755]
 [ 0.95179019 -0.08065715  0.37155176  0.26963774]
 [-0.47589509  2.09708596 -1.37110093 -1.01144654]
 [ 2.49844924  1.8551145   1.49584381  1.03828831]
 [ 0.59486887  0.64525722  0.54019556  0.5258546 ]
 [ 1.3087115   0.1613143   0.76505397  1.4226136 ]
 [-0.83281641  1.8551145  -1.03381331 -1.01144654]
 [-1.3087115   0.40328576 -1.20245712 -1.2676634 ]
 [ 1.3087115   0.40328576  1.10234159  1.4226136 ]
 [-0.23794755 -0.80657152  0.25912255  0.14152931]
 [-0.47589509  2.09708596 -1.14624252 -1.01144654]
 [ 1.54665905 -0.08065715  1.2147708   1.16639674]
 [ 0.71384264  0.40328576  0.42776636  0.39774617]
 [ 0.23794755 -0.32262861  0.42776636  0.39774617]
 [-1.66563282  0.40328576 -1.37110093 -1.2676634 ]
 [ 0.         -1.04854298  0.14669334  0.01342088]
 [-0.23794755 -0.08065715  0.42776636  0.39774617]
 [-0.47589509  0.88722867 -1.25867172 -1.01144654]
 [-0.95179019  0.40328576 -1.42

In [51]:
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_test)

['setosa' 'versicolor' 'versicolor' 'setosa' 'virginica' 'versicolor'
 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'virginica' 'versicolor' 'setosa' 'setosa' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica' 'setosa'
 'versicolor' 'setosa' 'versicolor' 'virginica' 'virginica' 'setosa'
 'versicolor' 'virginica' 'versicolor']
14         setosa
98     versicolor
75     versicolor
16         setosa
131     virginica
56     versicolor
141     virginica
44         setosa
29         setosa
120     virginica
94     versicolor
5          setosa
102     virginica
51     versicolor
78     versicolor
42         setosa
92     versicolor
66     versicolor
31         setosa
35         setosa
90     versicolor
84     versicolor
77     versicolor
40         setosa
125     virginica
99     versicolor
33     

In [56]:
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9555555555555556


In [57]:
print(confusion_matrix(y_test, y_pred))  

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


In [58]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.94      0.94      0.94        18
   virginica       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [78]:
classifier = KNeighborsClassifier() 

In [79]:
param_grid = {'n_neighbors': np.arange(1, 25)}

In [80]:
knn_gscv = GridSearchCV(classifier, param_grid, cv=5)

In [92]:
knn_gscv.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})

In [93]:
knn_gscv.best_params_

{'n_neighbors': 1}

In [94]:
knn_gscv.best_score_

0.9523809523809523

In [95]:
classifier = KNeighborsClassifier(n_neighbors = 1)  
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [96]:
y_pred = classifier.predict(x_test)

In [97]:
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9333333333333333
